Fix JS Dataviz: When dataviz is not available
In embed mode the error is generated because the dataviz elements are not available.
```
TypeError: elem is null
    isInViewport dataviz.js:23
    getPlots dataviz.js:146
    uicreated dataviz.js:774
    triggerEvent OpenLayers.js:246
    init map.js:5034
map.js:5039:28
    init map.js:5039
```