[Bugfix] lizmapWkt class does not well check point as numeric values
PHPStan - PHP Static Analysis Tool 1.10.1 provides an error message on lizmapWkt class:

```bash
Error: Negated boolean expression is always false.
 ------ --------------------------------------------------------------------
  Line   lizmap/classes/lizmapWkt.class.php
 ------ --------------------------------------------------------------------
  135    Negated boolean expression is always false.
         💡 Because the type is coming from a PHPDoc, you can turn off this
            check by setting treatPhpDocTypesAsCertain: false in your
            ../phpstan.neon.
 ------ --------------------------------------------------------------------
```

The error is due to a double `is_numeric` check on the same value.
lizmapWkt::parsePoint was checking twice if the first coordinates is a numeric and not if the two coordinates are numerics.

Funded by 3liz https://3liz.com